version: '2'
services:
    yupartymicroservices-mongodb:
        container_name: yupartymicroservices-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/YuPartyMicroservices/mongodb/:/data/db/
